language: python
dist: focal  
python:
  - "3.10"   

before_install:
  - sudo apt-get update
  - pip install flask

in stall:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install telebot pymongo aiohttp

script:
  - chmod +x * && chmod +x * bgmi && python3 sahil.py
